name: NPM Registry Publish

on: 
    push:
        branches:
            - "main"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile

    env: 
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run:  echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc && bun run publish